# Site settings
title: "Mithun Ghosh Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mithun Ghosh"
resume_title:                   "Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mithun.ghosh@hotmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "9769792429"
resume_contact_address:         "Flat 601, Block 13, Suncity Apartments, Ibblur, Bangalore, PIN 560102"

resume_header_contact_info:     "Flat 601 Block 13 GoldStrike, Suncty Apartments Ibblur • Bangalore • 9769704973 • mithunrecdgp@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>ML professional with 13 years of hands-on and managerial experience in developing ML powered products.
Specialties: Text analytics, data mining, machine learning, natural language processing, online advertising, knowledge representation, offline advertising optimization etc
Semantic parsing using a combination of grammars and machine learning (NLP)
Automated Question Answering system, query expansion and search augmentation
Building self-help system to solve real time user needs</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ghoshmithun/resume"
  resume_twitter_url:           "http://twitter.com/mithunrecdgp"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mithunghosh"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
